### ISSUE TITLE
Flagged users report

### ISSUE THREAD

**Issue by zereplim** [MicrosoftDocs/IntuneDocs.pt-pt#113]
How often does this report updates? I've deleted the flagged devices but they are still showing on the report. I see no documentation on this and options on  how to handle.
Thanks

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 7e9b9cef-c6da-8913-9326-665127b76bbe
* Version Independent ID: 2c1463f3-a6d1-6746-055a-7b5278040e6e
* Content: [Como monitorizar políticas de proteção de aplicações - Microsoft Intune](https://docs.microsoft.com/pt-pt/intune/app-protection-policies-monitor#feedback)
* Content Source: [intune/app-protection-policies-monitor.md](https://github.com/MicrosoftDocs/IntuneDocs.pt-pt/blob/live/intune/app-protection-policies-monitor.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Hello, @zereplim 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
